version: '3.8'
services:
    mysql:
      image: mysql:8.0.32
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: example